# A workflow to clean the repository from the mess of the Actions
# removes old actions runs and remaining branches of failed actions
name: 'Clean repository'

on:
  push:
  schedule:
    - cron: '0 8 * * *'

jobs:

  # delete previous runs
  del_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{github.repository}}
          keep_minimum_runs: 3
          retain_days: 1 # delete all but the latest, only keeping count

  # remove all branches with "updates" in them, as they are produced by the flake updating
  remove-branches:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Set up git
      run: |
        git config user.email "noe.perard+git@gmail.com"
        git config user.name "Git Bot"
    - name: Remove branches
      run: |
        for b in  $(git branch --remote | grep "/updates-[0-9]*" | sed  s/"origin\/"//);
        do
          git push origin --delete $b
        done
      env:
        GITHUB_TOKEN: ${{ github.token }}


  