name: Flake Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
   call-workflow-passing-data:
    uses: MadMcCrow/flake-github-workflow/.github/workflows/flake-update.yml@main
    with:
      git_email: noe.perard+git@gmail.com
      pr_message: ':robot::snowflake: flake.lock : update'
      commit_message: ':robot::snowflake: flake.lock : update'
    secrets:
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}