name: 'Update Flake.Lock'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  call-external-flake-update:
    uses: MadMcCrow/flake-github-workflow/main.yml@main
    with:
      git_email: noe.perard+git@gmail.com
    secrets:
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}