name: 'Update Flake.Lock'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:

  # nix flake update
  update-flake-reuse:
    uses: MadMcCrow/flake-github-workflow/.github/workflows/update_flake.yml@main
    with:
      git_email: noe.perard+git@gmail.com
      variables: ${{vars}}
    secrets:
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

  # pr
  #pull-request-reuse:
  #  needs: [update-flake-reuse]
  #  uses: MadMcCrow/flake-github-workflow/.github/workflows/pull_request.yaml@main
  #  with:
  #    commit:    'update : flake.lock'
  #    pr_title:  ':robot: flake update'

  # clean up
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 1
          delete_run_by_conclusion_pattern: success