name: 'Update Flake.Lock'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:

  # nix flake update
  update-flake-reuse:
    uses: MadMcCrow/flake-github-workflow/.github/workflows/update_flake.yml@main
    with:
      cachix-repository: godot-flake
      jq-command:  '.packages["x86_64-linux"] | keys - ["default"]'
      nix_extra_config: | # ${{vars.EXTRA_NIX_CONFIG}}
          auto-optimise-store = true
          access-tokens = github.com=${{ github.token }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    secrets:
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

  # pr
  #pull-request-reuse:
  #  needs: [update-flake-reuse]
  #  uses: MadMcCrow/flake-github-workflow/.github/workflows/pull_request.yaml@main
  #  with:
  #    commit:    'update : flake.lock'
  #    pr_title:  ':robot: flake update'

 # clean up (do it at the end)
 clean-workflow-reuse:
    needs: [ update-flake-reuse]
    uses: MadMcCrow/flake-github-workflow/.github/workflows/clean-workflows.yml@main
