name: 'Update Flake.Lock'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:

  # update flake inputs
  update-flake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup-nix
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: ${{inputs.nix_extra_config}}
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install
      - name: Update the flake
        run: nix flake update
      - name: Store flake.lock
        uses: actions/upload-artifact@v3
        with:
          name: flake_lock
          path: flake.lock

  update-flake-reuse:
    needs: [update-flake]
    uses: MadMcCrow/flake-github-workflow/.github/workflows/update_flake.yml@main


  # nix flake update
  build-flake-reuse:
    needs: [update-flake]
    uses: MadMcCrow/flake-github-workflow/.github/workflows/build_flake.yml@main
    with:
      cachix-repository: godot-flake
      jq-command:  '.packages["x86_64-linux"] | keys - ["default"]'
    secrets:
      CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}

  # pr
  #pull-request-reuse:
  #  needs: [update-flake-reuse]
  #  uses: MadMcCrow/flake-github-workflow/.github/workflows/pull_request.yaml@main
  #  with:
  #    commit:    'update : flake.lock'
  #    pr_title:  ':robot: flake update'

  # clean up (do it at the end)
  clean-workflow-reuse:
    # needs: [ update-flake-reuse]
    uses: MadMcCrow/flake-github-workflow/.github/workflows/clean_workflows.yml@main
    with:
      repository: ${{ github.repository }}